### ISSUE TITLE
Samsung Serie J

### ISSUE THREAD

**Issue by djavancosta** [bencarlisle15/AlexaControlledSamsungTV#5]
Hello !
I had TV model UN48JU6500 aI can not make the program work, can you help me?
The mistake I have today is when it is time to scan the TV:

Traceback (most recent call last):
   File "alexasmartcli.py", line 8, in <module>
     from helpers import mqtt_server
   File "/home/pi/AlexaControlledSamsungTV/helpers/mqtt_server.py", line 11, in <module>
     from SmartCrypto.smartcrypto import SmartCrypto
ImportError: can not import name 'SmartCrypto'

**Comment by barne77** [comment]
I have the same issue 
sessionId: 1
SessionID: 1
Authorization successfull :)

Traceback (most recent call last):
  File "alexasmartcli.py", line 8, in <module>
    from helpers import mqtt_server
  File "/home/pi/Documents/AlexaControlledSamsungTV/helpers/mqtt_server.py", line 11, in <module>
    from SmartCrypto.smartcrypto import SmartCrypto
ImportError: cannot import name 'SmartCrypto' from 'SmartCrypto.smartcrypto' (/home/pi/Documents/AlexaControlledSamsungTV/SmartCrypto/smartcrypto.py)
